/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Metohologio_example scene_v2.glb -o src/scene/Map/MetohologioSceneV2.tsx -T
*/

import * as THREE from 'three'
import React, { useMemo } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, useTexture } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'
import { CartoonBlobFiberMaterial } from '../Effects/material-shaders/CartoonBlobFiberMaterial'
import { CartoonBlobMaterial } from '../Effects/material-shaders/CartoonBlobMaterial'
import { assetUrl } from '../../utils/assetUrl.js'
import { usePlaneWallMaterial } from './usePlaneWallMaterial'

const modelUrl = assetUrl('assets/model/Map/Metohologio_example_scene_v2-transformed.glb')

type ActionName = 'Action.001' | 'Action.002' | 'Armature.004Action.002' | 'Armature.004Action.003' | 'Armature.004|Armature.002Action.001' | 'Armature.004|Armature.004Action.001' | 'Armature.005|Armature|3030509026704_TempMotion|3030509026704_Te' | 'Armature|3030509026704_TempMotion|3030509026704_TempMotion.002' | 'Armature|3030509026704_TempMotion|3030509026704_TempMotion.003' | 'Action.003' | 'Armature.004Action' | 'Armature.004Action.001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Small_Sheep: THREE.SkinnedMesh
    Large_Sheep: THREE.SkinnedMesh
    Wall_Plane: THREE.Mesh
    Stone001: THREE.Mesh
    Ground: THREE.Mesh
    Grass003: THREE.SkinnedMesh
    Grass001: THREE.SkinnedMesh
    Grass002: THREE.SkinnedMesh
    Grass004: THREE.SkinnedMesh
    Grass005: THREE.SkinnedMesh
    Grass006: THREE.SkinnedMesh
    Grass007: THREE.SkinnedMesh
    Grass: THREE.SkinnedMesh
    RL_BoneRoot: THREE.Bone
    RL_BoneRoot_1: THREE.Bone
    Bone: THREE.Bone
    Bone_1: THREE.Bone
    Bone_2: THREE.Bone
    Bone_3: THREE.Bone
    Bone_4: THREE.Bone
    Bone_5: THREE.Bone
    Bone_7: THREE.Bone
    Bone_6: THREE.Bone
  }
  materials: Record<'Material.002' | 'Ground_painterly.001', THREE.MeshStandardMaterial>
  animations: GLTFAction[]
}

export default function MetohologioSceneV2(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF(modelUrl)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  const wallTexture = useTexture(assetUrl('texture_atlas_no_red_v1.png'))
  const groundShadowTexture = useTexture(assetUrl('ground-path-inverted.png'))


  React.useEffect(() => {
    const activeActions = Object.values(actions)
    activeActions.forEach((action) => action?.reset().play())

    return () => {
      activeActions.forEach((action) => action?.stop())
    }
  }, [actions])

  // const material = useMemo(
  //   () =>
  //     new CartoonBlobFiberMaterial({
  //       inkColor: new THREE.Color(0.5, 0, 1),
  //       outlineColor: new THREE.Color(0.5, 0, 0),
  //       backgroundColor: new THREE.Color(0.5, 0.0, 0),
  //       edgeNoiseStrength: 0,
  //       edgeStart: 0.28,
  //       edgeEnd: 0.28,
  //       fiberScale: 3,
  //       fiberInfluence: 1,
  //       fiberRotationStep: 0.1,
  //       fiberThreshold: 0.3,
  //     }),
  //   []
  // )

  const material = useMemo(
    () =>
      new CartoonBlobMaterial({
        inkColor: new THREE.Color(0.56, 0.75, 1.0),
        outlineColor: new THREE.Color(0.0, 0.95, 0.82),
        backgroundColor: new THREE.Color(0.03, 0.08, 0.18),
        shadeColor: new THREE.Color(0.0, 0.0, 0.0),
        litColor: new THREE.Color(0.0, 0.0, 1.0),
        fiberScale: 1.8,
        fiberInfluence: 0.18,
        edgeNoiseStrength: 0.12,
        edgeStart: 0.22,
        edgeEnd: 0.52,
        bandCount: 4,
        blobScale: 0.5,
        blobAmount: 0.1,
        noiseScale: 20.0,
      }),
    []
  )


  const wallMaterial = useMemo(() => {
    wallTexture.colorSpace = THREE.SRGBColorSpace
    wallTexture.flipY = false
    wallTexture.wrapS = THREE.RepeatWrapping
    wallTexture.wrapT = THREE.RepeatWrapping
    wallTexture.repeat.set(1, 1)

    return new CartoonBlobFiberMaterial({
        inkColor: new THREE.Color(0.5, 1.9, 1.0),
        outlineColor: new THREE.Color(0.5, 0, 1.0),
        backgroundColor: new THREE.Color(0.5, 0.0, 1.0),
        edgeNoiseStrength: 0,
        edgeStart: 0.28,
        edgeEnd: 0.28,
        fiberScale: 3,
        fiberInfluence: 1,
        fiberRotationStep: 0.1,
        fiberThreshold: 0.3,
        useStaticCamera: true,
        shadowTexture: wallTexture,
        staticCameraPosition: [10, 10, 10],
        staticCameraTarget: [0, 0, 0],
        worldZStart: 0,
        worldZEnd: 10,
        side: THREE.DoubleSide
      })
  }, [materials, wallTexture])

  nodes.Small_Sheep.material = material
  nodes.Large_Sheep.material = material
  nodes.Grass003.material = material
  nodes.Grass001.material = material
  nodes.Grass002.material = material
  nodes.Grass004.material = material
  nodes.Grass005.material = material
  nodes.Grass006.material = material
  nodes.Grass007.material = material
  nodes.Grass.material = material
  nodes.Stone001.material = material

  const groundMaterial = useMemo(
    () =>
      new CartoonBlobFiberMaterial({
        inkColor: new THREE.Color(0.5, 0, 1),
        outlineColor: new THREE.Color(0.5, 0, 0),
        backgroundColor: new THREE.Color(0.5, 0.0, 0),
        edgeNoiseStrength: 0,
        edgeStart: 0.28,
        edgeEnd: 0.28,
        fiberScale: 3,
        fiberInfluence: 1,
        fiberRotationStep: 0.1,
        fiberThreshold: 0.3,
        useStaticCamera: true,
        shadowTexture: groundShadowTexture,
        staticCameraPosition: [0, 10, 10],
        staticCameraTarget: [0, 0, 0],
        worldZStart: 0,
        worldZEnd: 10,
      }),
    [groundShadowTexture]
  )
  return (
    <group castShadow receiveShadow ref={group} {...props} dispose={null}>
      <group castShadow receiveShadow name="Scene">
        {/* <group castShadow receiveShadow name="Small_Sheep_Armature" position={[3.301, -0.1, 3.002]} rotation={[0, -0.625, 0]} scale={0.637}>
          <primitive object={nodes.RL_BoneRoot} />
          <skinnedMesh castShadow receiveShadow name="Small_Sheep" geometry={nodes.Small_Sheep.geometry} material={nodes.Small_Sheep.material} skeleton={nodes.Small_Sheep.skeleton} />
        </group> */}
        <group castShadow receiveShadow name="Large_Sheep_Armature" position={[3.36, -0.037, 3.251]} rotation={[0, -1.415, 0]} scale={1.13}>
          <primitive object={nodes.RL_BoneRoot_1} />
          <skinnedMesh castShadow receiveShadow name="Large_Sheep" geometry={nodes.Large_Sheep.geometry} material={nodes.Large_Sheep.material} skeleton={nodes.Large_Sheep.skeleton} />
        </group>
        <group castShadow receiveShadow name="Grass_Armature003" position={[0.189, -0.052, 0.251]} rotation={[0, 0.133, 0]} scale={1.389}>
          <primitive object={nodes.Bone} />
        </group>
        <group castShadow receiveShadow name="Grass_Armature001" position={[1.069, -0.023, -0.465]} rotation={[0, 0.133, 0]} scale={2.502}>
          <primitive object={nodes.Bone_1} />
        </group>
        <group castShadow receiveShadow name="Grass_Armature002" position={[3.195, -0.023, -11.633]} rotation={[0, 0.133, 0]} scale={2.679}>
          <primitive object={nodes.Bone_2} />
        </group>
        <group castShadow receiveShadow name="Grass_Armature004" position={[3.76, 0.033, -11.568]} rotation={[0, 0.133, 0]} scale={4.825}>
          <primitive object={nodes.Bone_3} />
        </group>
        <group castShadow receiveShadow name="Grass_Armature005" position={[3.471, 0.065, -12.207]} rotation={[0, 0.672, 0]} scale={6.152}>
          <primitive object={nodes.Bone_4} />
        </group>
        <group castShadow receiveShadow name="Grass_Armature006" position={[2.596, 0.005, -11.713]} rotation={[0, 0.672, 0]} scale={3.694}>
          <primitive object={nodes.Bone_5} />
        </group>
        <group castShadow receiveShadow name="Grass_Armature007" position={[2.804, -0.009, -11.357]} rotation={[0, 0.133, 0]} scale={1.904}>
          <primitive object={nodes.Bone_7} />
        </group>
        <group castShadow receiveShadow name="Grass_Armature" position={[7.724, -0.143, -12.22]} rotation={[0, 0.133, 0]} scale={2.679}>
          <primitive object={nodes.Bone_6} />
        </group>
        <mesh name="Wall_Plane" geometry={nodes.Wall_Plane.geometry} material={wallMaterial} position={[8.543, 1.02, -8.262]} rotation={[0, 0, -Math.PI / 2]} />
        <mesh name="Stone001" geometry={nodes.Stone001.geometry} material={nodes.Stone001.material} position={[0.232, 0.249, -0.185]} scale={1.389} />
        <mesh name="Ground" geometry={nodes.Ground.geometry} material={groundMaterial} position={[0, -0.848, 0.267]} scale={1.811} castShadow receiveShadow />
        <skinnedMesh name="Grass003" geometry={nodes.Grass003.geometry} material={nodes.Grass003.material} skeleton={nodes.Grass003.skeleton} position={[0.189, -0.052, 0.251]} rotation={[0, 0.133, 0]} scale={1.389} />
        <skinnedMesh name="Grass001" geometry={nodes.Grass001.geometry} material={nodes.Grass001.material} skeleton={nodes.Grass001.skeleton} position={[1.069, -0.023, -0.465]} rotation={[0, 0.133, 0]} scale={2.502} />
        <skinnedMesh name="Grass002" geometry={nodes.Grass002.geometry} material={nodes.Grass002.material} skeleton={nodes.Grass002.skeleton} position={[3.195, -0.023, -11.633]} rotation={[0, 0.133, 0]} scale={2.679} />
        <skinnedMesh name="Grass004" geometry={nodes.Grass004.geometry} material={nodes.Grass004.material} skeleton={nodes.Grass004.skeleton} position={[3.76, 0.033, -11.568]} rotation={[0, 0.133, 0]} scale={4.825} />
        <skinnedMesh name="Grass005" geometry={nodes.Grass005.geometry} material={nodes.Grass005.material} skeleton={nodes.Grass005.skeleton} position={[3.471, 0.065, -12.207]} rotation={[0, 0.672, 0]} scale={6.152} />
        <skinnedMesh name="Grass006" geometry={nodes.Grass006.geometry} material={nodes.Grass006.material} skeleton={nodes.Grass006.skeleton} position={[2.596, 0.005, -11.713]} rotation={[0, 0.672, 0]} scale={3.694} />
        <skinnedMesh name="Grass007" geometry={nodes.Grass007.geometry} material={nodes.Grass007.material} skeleton={nodes.Grass007.skeleton} position={[2.804, -0.009, -11.357]} rotation={[0, 0.133, 0]} scale={1.904} />
        <skinnedMesh name="Grass" geometry={nodes.Grass.geometry} material={nodes.Grass.material} skeleton={nodes.Grass.skeleton} position={[7.724, -0.143, -12.22]} rotation={[0, 0.133, 0]} scale={2.679} />
      </group>
    </group>
  )
}

useGLTF.preload(modelUrl)
