/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Metohologio_example scene_v1.glb -o src/scene/Map/MetohologioScene.tsx -T
*/

import * as THREE from 'three'
import React, { useMemo } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'
import { CartoonBlobMaterial } from '../Effects/material-shaders/CartoonBlobMaterial'
import { Color } from 'three'

const modelUrl = '/assets/model/Map/Metohologio_example_scene_v1-transformed.glb'

type ActionName = 'Action.004' | 'Action.005' | 'Armature.004Action.004' | 'Armature.004Action.005' | 'Armature.004|Armature.002Action.002' | 'Armature.004|Armature.004Action.002' | 'Armature.005|Armature|3030509026704_TempMotion|3030509026704_Te' | 'Armature|3030509026704_TempMotion|3030509026704_TempMotion.001' | 'Armature|3030509026704_TempMotion|3030509026704_TempMotion.004' | 'Action.006' | 'Armature.004Action' | 'Armature.004Action.001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Large_Sheep: THREE.SkinnedMesh
    Small_Sheep: THREE.SkinnedMesh
    Stone001: THREE.Mesh
    Ground: THREE.Mesh
    Wall: THREE.Mesh
    Grass003: THREE.SkinnedMesh
    Grass001: THREE.SkinnedMesh
    Grass002: THREE.SkinnedMesh
    Grass004: THREE.SkinnedMesh
    Grass005: THREE.SkinnedMesh
    Grass006: THREE.SkinnedMesh
    Grass007: THREE.SkinnedMesh
    Grass: THREE.SkinnedMesh
    RL_BoneRoot: THREE.Bone
    RL_BoneRoot_1: THREE.Bone
    Bone: THREE.Bone
    Bone_1: THREE.Bone
    Bone_2: THREE.Bone
    Bone_3: THREE.Bone
    Bone_4: THREE.Bone
    Bone_5: THREE.Bone
    Bone_7: THREE.Bone
    Bone_6: THREE.Bone
  }
  materials: Record<'painterly.002', THREE.MeshStandardMaterial>
  animations: GLTFAction[]
}

export default function MetohologioScene(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF(modelUrl)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)

  const material = useMemo(
    () =>
      new CartoonBlobMaterial({
        color: new Color(0.56, 0.75, 1.0),
        edgeColor: new Color(0.02, 0.95, 0.82),
        shadowColor: new Color(0.03, 0.08, 0.18),
        lightColor: new Color(0.48, 0.86, 1.0),
        blobAmount: 0.,
        blobScale: 1,
        edgeNoiseStrength: 0.3,
        edgeStart: 0.,
        edgeEnd: 0.9,
        bandCount: 6,
      }),
    []
  )

  React.useEffect(() => {
    const activeActions = Object.values(actions)
    activeActions.forEach((action) => action?.reset().play())

    return () => {
      activeActions.forEach((action) => action?.stop())
    }
  }, [actions])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Large_Sheep_Armature" position={[3.36, -0.037, 3.251]} rotation={[0, -1.415, 0]} scale={1.13}>
          <primitive object={nodes.RL_BoneRoot} />
          <skinnedMesh name="Large_Sheep" geometry={nodes.Large_Sheep.geometry} material={material} skeleton={nodes.Large_Sheep.skeleton} />
        </group>
        <group name="Small_Sheep_Armature" position={[3.301, -0.1, 3.002]} rotation={[0, -0.625, 0]} scale={0.637}>
          <primitive object={nodes.RL_BoneRoot_1} />
          {/* <skinnedMesh name="Small_Sheep" geometry={nodes.Small_Sheep.geometry} material={material} skeleton={nodes.Small_Sheep.skeleton} /> */}
        </group>
        <group name="Grass_Armature003" position={[0.189, -0.052, 0.251]} rotation={[0, 0.133, 0]} scale={1.389}>
          <primitive object={nodes.Bone} />
        </group>
        <group name="Grass_Armature001" position={[1.069, -0.023, -0.465]} rotation={[0, 0.133, 0]} scale={2.502}>
          <primitive object={nodes.Bone_1} />
        </group>
        <group name="Grass_Armature002" position={[3.195, -0.023, -11.633]} rotation={[0, 0.133, 0]} scale={2.679}>
          <primitive object={nodes.Bone_2} />
        </group>
        <group name="Grass_Armature004" position={[3.76, 0.033, -11.568]} rotation={[0, 0.133, 0]} scale={4.825}>
          <primitive object={nodes.Bone_3} />
        </group>
        <group name="Grass_Armature005" position={[3.471, 0.065, -12.207]} rotation={[0, 0.672, 0]} scale={6.152}>
          <primitive object={nodes.Bone_4} />
        </group>
        <group name="Grass_Armature006" position={[2.596, 0.005, -11.713]} rotation={[0, 0.672, 0]} scale={3.694}>
          <primitive object={nodes.Bone_5} />
        </group>
        <group name="Grass_Armature007" position={[2.804, -0.009, -11.357]} rotation={[0, 0.133, 0]} scale={1.904}>
          <primitive object={nodes.Bone_7} />
        </group>
        <group name="Grass_Armature" position={[7.724, -0.143, -12.22]} rotation={[0, 0.133, 0]} scale={2.679}>
          <primitive object={nodes.Bone_6} />
        </group>
        <mesh name="Stone001" geometry={nodes.Stone001.geometry} material={material} position={[0.232, 0.249, -0.185]} scale={1.389} />
        <mesh name="Ground" geometry={nodes.Ground.geometry} material={materials['painterly.002']} position={[0, -0.848, 0.267]} scale={1.811} />
        <mesh name="Wall" geometry={nodes.Wall.geometry} material={materials['painterly.002']} />
        <skinnedMesh name="Grass003" geometry={nodes.Grass003.geometry} material={materials['painterly.002']} skeleton={nodes.Grass003.skeleton} position={[0.189, -0.052, 0.251]} rotation={[0, 0.133, 0]} scale={1.389} />
        <skinnedMesh name="Grass001" geometry={nodes.Grass001.geometry} material={materials['painterly.002']} skeleton={nodes.Grass001.skeleton} position={[1.069, -0.023, -0.465]} rotation={[0, 0.133, 0]} scale={2.502} />
        <skinnedMesh name="Grass002" geometry={nodes.Grass002.geometry} material={materials['painterly.002']} skeleton={nodes.Grass002.skeleton} position={[3.195, -0.023, -11.633]} rotation={[0, 0.133, 0]} scale={2.679} />
        <skinnedMesh name="Grass004" geometry={nodes.Grass004.geometry} material={materials['painterly.002']} skeleton={nodes.Grass004.skeleton} position={[3.76, 0.033, -11.568]} rotation={[0, 0.133, 0]} scale={4.825} />
        <skinnedMesh name="Grass005" geometry={nodes.Grass005.geometry} material={materials['painterly.002']} skeleton={nodes.Grass005.skeleton} position={[3.471, 0.065, -12.207]} rotation={[0, 0.672, 0]} scale={6.152} />
        <skinnedMesh name="Grass006" geometry={nodes.Grass006.geometry} material={materials['painterly.002']} skeleton={nodes.Grass006.skeleton} position={[2.596, 0.005, -11.713]} rotation={[0, 0.672, 0]} scale={3.694} />
        <skinnedMesh name="Grass007" geometry={nodes.Grass007.geometry} material={materials['painterly.002']} skeleton={nodes.Grass007.skeleton} position={[2.804, -0.009, -11.357]} rotation={[0, 0.133, 0]} scale={1.904} />
        <skinnedMesh name="Grass" geometry={nodes.Grass.geometry} material={materials['painterly.002']} skeleton={nodes.Grass.skeleton} position={[7.724, -0.143, -12.22]} rotation={[0, 0.133, 0]} scale={2.679} />
      </group>
    </group>
  )
}

useGLTF.preload(modelUrl)
