/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Metohologio_example scene_v2.glb -o src/scene/Map/MetohologioSceneV2.tsx -T
*/

import * as THREE from 'three'
import React, { useMemo } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations, useTexture } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'
import { CartoonBlobFiberMaterial } from '../Effects/material-shaders/CartoonBlobFiberMaterial'
import { assetUrl } from '../../utils/assetUrl.js'

const modelUrl = assetUrl('assets/model/Map/Metohologio_example_scene_v2-transformed.glb')

type ActionName = 'Action.001' | 'Action.002' | 'Armature.004Action.002' | 'Armature.004Action.003' | 'Armature.004|Armature.002Action.001' | 'Armature.004|Armature.004Action.001' | 'Armature.005|Armature|3030509026704_TempMotion|3030509026704_Te' | 'Armature|3030509026704_TempMotion|3030509026704_TempMotion.002' | 'Armature|3030509026704_TempMotion|3030509026704_TempMotion.003' | 'Action.003' | 'Armature.004Action' | 'Armature.004Action.001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Small_Sheep: THREE.SkinnedMesh
    Large_Sheep: THREE.SkinnedMesh
    Wall_Plane: THREE.Mesh
    Stone001: THREE.Mesh
    Ground: THREE.Mesh
    Grass003: THREE.SkinnedMesh
    Grass001: THREE.SkinnedMesh
    Grass002: THREE.SkinnedMesh
    Grass004: THREE.SkinnedMesh
    Grass005: THREE.SkinnedMesh
    Grass006: THREE.SkinnedMesh
    Grass007: THREE.SkinnedMesh
    Grass: THREE.SkinnedMesh
    RL_BoneRoot: THREE.Bone
    RL_BoneRoot_1: THREE.Bone
    Bone: THREE.Bone
    Bone_1: THREE.Bone
    Bone_2: THREE.Bone
    Bone_3: THREE.Bone
    Bone_4: THREE.Bone
    Bone_5: THREE.Bone
    Bone_7: THREE.Bone
    Bone_6: THREE.Bone
  }
  materials: Record<'Material.002' | 'Ground_painterly.001', THREE.MeshStandardMaterial>
  animations: GLTFAction[]
}

export default function MetohologioSceneV2(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { scene, animations } = useGLTF(modelUrl)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  const { actions } = useAnimations(animations, group)
  const wallTexture = useTexture(assetUrl('texture_atlas_no_red_v1.png'))
  const groundShadowTexture = useTexture(assetUrl('ground-path-inverted.png'))


  React.useEffect(() => {
    const activeActions = Object.values(actions)
    activeActions.forEach((action) => action?.reset().play())

    return () => {
      activeActions.forEach((action) => action?.stop())
    }
  }, [actions])

  const material = useMemo(
    () =>
      new CartoonBlobFiberMaterial({
        backgroundLight: 0.15,
        edgeNoiseStrength: 0,
        edgeStart: 0.28,
        edgeEnd: 0.28,
        fiberScale: 3,
      }),
    []
  )


  const wallMaterial = useMemo(() => {
    wallTexture.colorSpace = THREE.SRGBColorSpace
    wallTexture.flipY = false
    wallTexture.wrapS = THREE.RepeatWrapping
    wallTexture.wrapT = THREE.RepeatWrapping
    wallTexture.repeat.set(1, 1)

    return new CartoonBlobFiberMaterial({
        backgroundLight: 0.26,
        edgeNoiseStrength: 0,
        edgeStart: 0.28,
        edgeEnd: 0.28,
        fiberScale: 3,
        useStaticCamera: true,
        shadowTexture: wallTexture,
        staticCameraPosition: [10, 10, 10],
        staticCameraTarget: [0, 0, 0],
        worldZStart: 0,
        worldZEnd: 10,
        side: THREE.DoubleSide
      })
  }, [materials, wallTexture])


  return (
    <group castShadow receiveShadow ref={group} {...props} dispose={null}>
      <group castShadow receiveShadow name="Scene">
        <mesh name="Wall_Plane" geometry={nodes.Wall_Plane.geometry} material={wallMaterial} position={[8.543, 1.02, -8.262]} rotation={[0, 0, -Math.PI / 2]} />
      </group>
    </group>
  )
}

useGLTF.preload(modelUrl)
