/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./Map_Monuments_v18.glb -o ../../../assets/model/Map/Monuments.tsx -r ../../../ -E -d /draco -T -j -I 
Files: ./Map_Monuments_v18.glb [1.05MB] > /Users/dimitrisgkegkas/Enneas/Thessaloniki/src/Components/MainCanvas/Map/Map_Monuments_v19-transformed.glb [521.6KB] (50%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { mergeAndColorGeometries } from './helper'

type GLTFResult = GLTF & {
    nodes: {
        White_Tower_1: THREE.Mesh
        White_Tower_2: THREE.Mesh
        White_Tower_3: THREE.Mesh
        White_Tower_4: THREE.Mesh
        Rotunda_1: THREE.Mesh
        Rotunda_2: THREE.Mesh
        Rotunda_3: THREE.Mesh
        Rotunda_4: THREE.Mesh
        Rotunda_5: THREE.Mesh
        Kamara_1: THREE.Mesh
        Kamara_2: THREE.Mesh
        Kamara_3: THREE.Mesh
        Old_Railway_Station_1: THREE.Mesh
        Old_Railway_Station_2: THREE.Mesh
        Old_Railway_Station_3: THREE.Mesh
        Old_Railway_Station_4: THREE.Mesh
        Old_Railway_Station_5: THREE.Mesh
        Old_Railway_Station_6: THREE.Mesh
        Makabi_football: THREE.Mesh
        Makabi_football_1: THREE.Mesh
        Makabi_football_2: THREE.Mesh
        Makabi_football_3: THREE.Mesh
        Makabi_football_4: THREE.Mesh
        Makabi_football_5: THREE.Mesh
        Makabi_football_6: THREE.Mesh
        Makabi_football_7: THREE.Mesh
        Makabi_football_8: THREE.Mesh
        Makabi_football_9: THREE.Mesh
        Makabi_football_10: THREE.Mesh
        Makabi_football_11: THREE.Mesh
        Walls: THREE.Mesh
        Jewish_Community_School_1: THREE.Mesh
        Jewish_Community_School_2: THREE.Mesh
        Jewish_Community_School_3: THREE.Mesh
        Jewish_Community_School_4: THREE.Mesh
        Jewish_Community_School_5: THREE.Mesh
        Jewish_Community_Offices_1: THREE.Mesh
        Jewish_Community_Offices_2: THREE.Mesh
        Jewish_Community_Offices_3: THREE.Mesh
        Jewish_Community_Offices_4: THREE.Mesh
        Jewish_Community_Offices_5: THREE.Mesh
        Jewish_Community_Offices_6: THREE.Mesh
        Cube015: THREE.Mesh
        Cube015_1: THREE.Mesh
        Cube015_2: THREE.Mesh
        Cube015_3: THREE.Mesh
        Cube015_4: THREE.Mesh
        Cube015_5: THREE.Mesh
        Plateia_Eleutherias: THREE.Mesh
        Pelosof001: THREE.Mesh
        Pelosof001_1: THREE.Mesh
        Pelosof001_2: THREE.Mesh
        Pelosof001_3: THREE.Mesh
        Pelosof001_4: THREE.Mesh
        Pelosof001_5: THREE.Mesh
        Holocaust_Museum_1: THREE.Mesh
        Holocaust_Museum_2: THREE.Mesh
        Rails_1: THREE.Mesh
        Rails_2: THREE.Mesh
        Rails002_1: THREE.Mesh
        Rails002_2: THREE.Mesh
        Rails003_1: THREE.Mesh
        Rails003_2: THREE.Mesh
        Train_Coach_1: THREE.Mesh
        Train_Coach_2: THREE.Mesh
        Train_Coach_3: THREE.Mesh
    }
    materials: {
        PaletteMaterial001: THREE.MeshStandardMaterial
        PaletteMaterial002: THREE.MeshStandardMaterial
        PaletteMaterial003: THREE.MeshStandardMaterial
        PaletteMaterial004: THREE.MeshStandardMaterial
        PaletteMaterial005: THREE.MeshStandardMaterial
    }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

const context = React.createContext({} as ContextType)

export function Instances({ children, ...props }: JSX.IntrinsicElements['group']) {
    const { nodes } = useGLTF('/assets/model/Map/Map_Monuments_v19-transformed.glb') as GLTFResult
    const instances = React.useMemo(
        () => ({
            TrainCoach: mergeAndColorGeometries(
                nodes,
                ['Train_Coach_1', 'Train_Coach_2', 'Train_Coach_3'],
                [new THREE.Color(0.5, 0.5, 3), new THREE.Color(0.5, 0.1, 0.1), new THREE.Color(0.5, 0.1, 0.6)]
            ),
            WhiteTower: mergeAndColorGeometries(
                nodes,
                ['White_Tower_1', 'White_Tower_2', 'White_Tower_3', 'White_Tower_4'],
                [new THREE.Color(0.5, 0.1, 0.3), new THREE.Color(0.5, 0.2, 2), new THREE.Color(0.8, 0.1, 0.5), new THREE.Color(0.5, 0.2, 1.2)]
            ),
            Rotunda: mergeAndColorGeometries(
                nodes,
                ['Rotunda_1', 'Rotunda_2', 'Rotunda_3', 'Rotunda_4', 'Rotunda_5'],
                [
                    new THREE.Color(0.5, 0.2, 0.9),
                    new THREE.Color(0.5, 0.17, 0.9),
                    new THREE.Color(0.5, 0.0, 2),
                    new THREE.Color(0.5, 0.25, 1.5),
                    new THREE.Color(0.5, 0.1, 1.8),
                ]
            ),
            Kamara: mergeAndColorGeometries(
                nodes,
                ['Kamara_1', 'Kamara_2', 'Kamara_3'],
                [new THREE.Color(0.5, 0, 0.1), new THREE.Color(0.5, 0.35, 0.5), new THREE.Color(0.5, 0.3, 0.2)]
            ),
            OldRailwayStation: mergeAndColorGeometries(
                nodes,
                [
                    'Old_Railway_Station_1',
                    'Old_Railway_Station_2',
                    'Old_Railway_Station_3',
                    'Old_Railway_Station_4',
                    'Old_Railway_Station_5',
                    'Old_Railway_Station_6',
                ],
                [
                    new THREE.Color(0.5, 0.1, 0.2),
                    new THREE.Color(0.0, 0.0, 0.95),
                    new THREE.Color(0.5, 0.1, 1),
                    new THREE.Color(0.5, 0.1, 0.7),
                    new THREE.Color(0, 0.0, 0.8),
                    new THREE.Color(0.5, 0.4, 0.3),
                ]
            ),
            Walls: mergeAndColorGeometries(nodes, ['Walls'], [new THREE.Color(0.5, 0.15, 1.5)]),

            Makabifootball: mergeAndColorGeometries(
                nodes,
                [
                    'Makabi_football',
                    'Makabi_football_1',
                    'Makabi_football_2',
                    'Makabi_football_3',
                    'Makabi_football_4',
                    'Makabi_football_5',
                    'Makabi_football_6',
                    'Makabi_football_7',
                    'Makabi_football_8',
                    'Makabi_football_9',
                    'Makabi_football_10',
                    'Makabi_football_11',
                ],
                [
                    new THREE.Color(0.5, 0.6, 0.9),
                    new THREE.Color(0.0, 0.0, 0.05),
                    new THREE.Color(0.5, 0.0, 0.9),
                    new THREE.Color(0.5, 0.0, 1),
                    new THREE.Color(0, 0.0, 1),
                    new THREE.Color(0.5, 0.0, 0.7),
                    new THREE.Color(0.5, 0.0, 0.5),
                    new THREE.Color(0.0, 0.0, 0.7),
                    new THREE.Color(0.5, 0.0, 0.1),
                    new THREE.Color(0.5, 0.0, 0.7),
                    new THREE.Color(0.5, 0.0, 0.3),
                    new THREE.Color(0.5, 0.1, 0.2),
                ]
            ),
            JewishCommunitySchool: mergeAndColorGeometries(
                nodes,
                [
                    'Jewish_Community_School_1',
                    'Jewish_Community_School_2',
                    'Jewish_Community_School_3',
                    'Jewish_Community_School_4',
                    'Jewish_Community_School_5',
                ],
                [
                    new THREE.Color(0.5, 0.15, 1),
                    new THREE.Color(0.0, 0.4, 0.7),
                    new THREE.Color(0.5, 0.1, 1),
                    new THREE.Color(0.5, 0.1, 1),
                    new THREE.Color(0, 0.0, 0.9),
                ]
            ),
            JewishCommunityOffices: mergeAndColorGeometries(
                nodes,
                [
                    'Jewish_Community_Offices_1',
                    'Jewish_Community_Offices_2',
                    'Jewish_Community_Offices_3',
                    'Jewish_Community_Offices_4',
                    'Jewish_Community_Offices_5',
                    'Jewish_Community_Offices_6',
                ],
                [
                    new THREE.Color(0.5, 0.4, 0.7),
                    new THREE.Color(0.5, 0.0, 0.8),
                    new THREE.Color(0.5, 0.05, 1),
                    new THREE.Color(0.5, 0.0, 0.7),
                    new THREE.Color(0.5, 0.0, 1),
                    new THREE.Color(0.5, 0.05, 1),
                ]
            ),
            Cube: mergeAndColorGeometries(
                nodes,
                ['Cube015', 'Cube015_1', 'Cube015_2', 'Cube015_3', 'Cube015_4', 'Cube015_5'],
                [
                    new THREE.Color(0.5, 0.2, 1),
                    new THREE.Color(0.5, 0.35, 0.3),
                    new THREE.Color(0.5, 0.05, 1),
                    new THREE.Color(0.5, 0.1, 0.9),
                    new THREE.Color(0.5, 0.1, 1),
                    new THREE.Color(0.5, 0.0, 0.7),
                ]
            ),
            PlateiaEleutherias: mergeAndColorGeometries(nodes, ['Plateia_Eleutherias'], [new THREE.Color(0.5, 0.4, 0.3)]),
            TrainTruck1: mergeAndColorGeometries(nodes, ['Rails_1', 'Rails_2'], [new THREE.Color(0.5, 0.3, 2), new THREE.Color(0.5, 0.4, 1)]),
            TrainTruck2: mergeAndColorGeometries(nodes, ['Rails002_1', 'Rails002_2'], [new THREE.Color(0.5, 0.3, 2), new THREE.Color(0.5, 0.4, 1)]),
            TrainTruck3: mergeAndColorGeometries(nodes, ['Rails003_1', 'Rails003_2'], [new THREE.Color(0.5, 0.3, 2), new THREE.Color(0.5, 0.4, 1)]),
            Pelosof: mergeAndColorGeometries(
                nodes,
                ['Pelosof001', 'Pelosof001_1', 'Pelosof001_2', 'Pelosof001_3', 'Pelosof001_4', 'Pelosof001_5'],
                [
                    new THREE.Color(0.5, 0.1, 0.5),
                    new THREE.Color(0.5, 0.4, 10.3),
                    new THREE.Color(0.9, 0.04, 0.9),
                    new THREE.Color(0, 0.9, 0.2),
                    new THREE.Color(0, 0.2, 3),
                    new THREE.Color(0.8, 0.2, 0.4),
                ]
            ),
            Museum: mergeAndColorGeometries(
                nodes,
                ['Holocaust_Museum_1', 'Holocaust_Museum_2'],
                [new THREE.Color(0.5, 0.1, 0.6), new THREE.Color(0.1, 1, 0.4)]
            ),
        }),
        [nodes]
    )
    return (
        <Merged meshes={instances} {...props}>
            {(instances: ContextType) => <context.Provider value={instances} children={children} />}
        </Merged>
    )
}

export default function Model(props: JSX.IntrinsicElements['group']) {
    const instances = React.useContext(context)
    return (
        <group {...props} dispose={null}>
            <instances.WhiteTower position={[-4.794, -0.567, -5.271]} rotation={[0.028, 0.013, -0.016]} scale={10.263} />
            <instances.Rotunda position={[-1.485, 0.255, -14.401]} rotation={[0.063, -0.025, 0.021]} scale={4.723} />
            <instances.Kamara position={[-2.466, -0.016, -11.967]} rotation={[0.04, 0.013, -0.016]} scale={0.104} />
            <instances.OldRailwayStation position={[-25.122, -0.604, -21.966]} scale={1.666} />
            <instances.Makabifootball position={[12.44, -0.159, 23.606]} rotation={[0, -1.294, -0.03]} scale={[0.924, 0.115, 0.924]} />
            <instances.Makabifootball position={[0.625, 0.017, -10.591]} rotation={[-3.022, 0.584, 3.072]} scale={[0.924, 0.115, 0.924]} />
            <instances.Makabifootball position={[3.899, -0.27, 14.982]} rotation={[-0.002, 0.04, 0.019]} scale={[0.708, 0.088, 0.708]} />
            <instances.Walls position={[2.049, 2.539, -23.338]} rotation={[0, -0.022, 0]} scale={0.015} />
            <instances.JewishCommunitySchool position={[5.765, -0.219, 5.24]} rotation={[-0.018, 0.759, 0.051]} scale={0.033} />
            <instances.JewishCommunityOffices position={[1.311, -0.38, 1.096]} rotation={[3.118, -0.256, 3.113]} scale={0.102} />
            <instances.Cube position={[4.92, 0.013, 8.705]} rotation={[3.134, -0.327, 3.127]} scale={0.253} />
            <instances.PlateiaEleutherias position={[-14.195, -0.337, -13.67]} />
            <instances.TrainCoach position={[-25.896, -0.424, -20.779]} rotation={[0, -0.333, 0]} scale={[0.402, 0.136, 0.136]} />
            <instances.TrainCoach position={[-24.163, -0.403, -20.631]} rotation={[0, -0.333, 0]} scale={[0.402, 0.136, 0.136]} />
            <instances.TrainCoach position={[-23.301, -0.403, -20.333]} rotation={[0, -0.333, 0]} scale={[0.402, 0.136, 0.136]} />
            <instances.TrainCoach position={[-25.064, -0.424, -20.493]} rotation={[0, -0.333, 0]} scale={[0.402, 0.136, 0.136]} />
            <instances.TrainTruck1 position={[2.917, 0, -13.274]} rotation={[0, Math.PI / 2, 0]} />
            <instances.TrainTruck2 position={[3.556, 0, -13.274]} rotation={[0, Math.PI / 2, 0]} />
            <instances.TrainTruck3 position={[-9.219, -0.033, -17.987]} rotation={[0, Math.PI / 2, 0]} />
            <instances.Pelosof position={[-12.423, -0.408, -13.609]} rotation={[0.012, 0.94, 0.004]} scale={0.057} />
            <instances.Museum position={[-28.959, -0.576, -26.528]} rotation={[-Math.PI, 0.175, -Math.PI]} scale={1.609} />
        </group>
    )
}

useGLTF.preload('/assets/model/Map/Map_Monuments_v19-transformed.glb')
